### ISSUE TITLE
Undefined array key warning with zh_TW locale

### ISSUE THREAD

**Issue by campbell-m** [flack/ranger#14]
If I run the following test code:

~~~php
<?php
use OpenPsa\Ranger\Ranger;

require_once 'lib/autoload.inc';

error_reporting(-1);
ini_set('display_errors', '1');

foreach (['en_GB', 'zh_TW'] as $locale) {
    $ranger = new Ranger($locale);
    $ranger
        ->setDateType(IntlDateFormatter::MEDIUM)
        ->setTimeType(IntlDateFormatter::SHORT);
    echo $ranger->format(1711738800, 1711738800);
    echo "<br>\n";
}
~~~

I get the output

~~~text
29 Mar 2024, 19:00
Warning: Undefined array key 8 in C:\inetpub\wwwroot\mrbs-main\lib\OpenPsa\Ranger\Ranger.php on line 195 Warning: Trying to access array offset on null in C:\inetpub\wwwroot\mrbs-main\lib\OpenPsa\Ranger\Ranger.php on line 195 2024年3月日, B日, B::
~~~

I am running the latest version of Ranger downloaded from the Master branch today using PHP 8.3.3 on Windows.

**Comment by flack** [comment]
Hi!

I have just added a commit that should solve this particular issue, even though I can't really say whether or not this is all that is required to properly support zh_TW locale.

Can you maybe help me out with something? I have written a unit test based on your code above, and locally, I get `2024年3月29日, 晚上7:00` as the result. When the same unit test runs on github, the result is `2024年3月29日, 下午7:00`. Which of those is the correct one, and what exactly is the difference?

**Comment by campbell-m** [comment]
Many thanks.  That seems to fix the PHP warning, but, like you, I have no idea what the answer should look like!  I'm just a developer on the [MRBS](https://github.com/meeting-room-booking-system) project which supports many locales.   I came across the problem while testing some changes I've made to our project.  However, I'll ask our mailing list to see if any zh_TW speakers can help.

**Comment by campbell-m** [comment]
It may be that both are correct and it just depends which version of the ICU library is being used.  Have you got different versions locally and on GitHub?  It could be that the pattern returned by `IntlDateFormatter::SHORT` for the time type has changed for the zh_TW locale.

**Comment by flack** [comment]
@campbell-m true, that actually happened once before (see e65cbf3a8ecd03689fdd0585f449c260facc3768). Still, it would be good to get some confirmation. According to wikipedia (assuming I read this correctly) [下午](https://en.wiktionary.org/wiki/%E4%B8%8B%E5%8D%88) and [晚上](https://en.wiktionary.org/wiki/%E6%99%9A%E4%B8%8A) seem to be different times, but like I said, I'm only guessing at this point :-)

**Comment by campbell-m** [comment]
I suspect it also has something to do with the differences between the ['a', 'b' and 'B' symbols](https://unicode-org.github.io/icu/userguide/format_parse/datetime/), which I'm trying to understand.  That's because we have an emulation of IntlDateFormatter that maps patterns onto the nearest `strftime()` equivalent for sites that don't have the 'intl' extension enabled.  As far as I can see zh_TW is the only locale that uses the 'B' symbol.

Anyway, I've asked our mailing list to comment here if anybody can help.

**Comment by flack** [comment]
yeah, it seems the pattern changed from `y年M月d日, ah:mm` to `y年M月d日, Bh:mm` at some point between ICU 66.1 and 73.2 (that's the only two versions I have available for testing currently). Will try to narrow it down, but in any case it looks like an ICU issue

**Comment by flack** [comment]
I've narrowed it down now to between version 67.1 and 70.1 and adjusted the testcase accordingly, so I guess this should be fixed for now.

**Comment by campbell-m** [comment]
Thanks.  Out of interest I wrote a test program to display the times in the zh_TW locale for each hour from 0..23 and for each of the three patterns 'a', 'b' and 'B':

~~~text
ah:mm	bh:mm	Bh:mm
上午12:00	上午12:00	凌晨12:00
上午1:00	上午1:00	凌晨1:00
上午2:00	上午2:00	凌晨2:00
上午3:00	上午3:00	凌晨3:00
上午4:00	上午4:00	凌晨4:00
上午5:00	上午5:00	清晨5:00
上午6:00	上午6:00	清晨6:00
上午7:00	上午7:00	清晨7:00
上午8:00	上午8:00	上午8:00
上午9:00	上午9:00	上午9:00
上午10:00	上午10:00	上午10:00
上午11:00	上午11:00	上午11:00
下午12:00	下午12:00	中午12:00
下午1:00	下午1:00	下午1:00
下午2:00	下午2:00	下午2:00
下午3:00	下午3:00	下午3:00
下午4:00	下午4:00	下午4:00
下午5:00	下午5:00	下午5:00
下午6:00	下午6:00	下午6:00
下午7:00	下午7:00	晚上7:00
下午8:00	下午8:00	晚上8:00
下午9:00	下午9:00	晚上9:00
下午10:00	下午10:00	晚上10:00
下午11:00	下午11:00	晚上11:00
~~~
