### ISSUE TITLE
dates with timezones specified as offsets cause IntlDateFormatter construct exception

### ISSUE THREAD

**Issue by ahebrank** [flack/ranger#2]
This is an edge case, but if your environment uses UTC offsets rather than named timezones:

```
$time = new \DateTime('2019-01-01')
$time->setTimezone(new \DateTimeZone('-0400'));
```

and then pass this into Ranger, you'll get this error:

```
IntlException: datefmt_create: no such time zone: '-0400': U_ILLEGAL_ARGUMENT_ERROR
```

Luckily there's an easy fix: initialize `IntlDateFormatter` with the DateTimeZone object, rather than the name (see "timezone" parameter on http://php.net/manual/en/intldateformatter.create.php)

PR incoming.

**Comment by flack** [comment]
> PR incoming.

Awesome! :-) 

I guess using `DateTimeZone` means we have to bump our minimum required PHP version, but 5.5 instead of 5.4 is still pretty generous.

**Comment by ahebrank** [comment]
You're right, didn't see that changelog note.

This is also a bit weirder than I thought with PHP 5 and 7 doing some different tz handling in the CI tests.
