### ISSUE TITLE
Minor formatting issue when using the "es" locale

### ISSUE THREAD

**Issue by javiereguiluz** [flack/ranger#4]
Hi! Thanks a lot for publishing this handy library! I was formatting some date range in my PHP 7.4 app like this:

```php
return (new Ranger($this->getLocale()))
    ->setDateType(\IntlDateFormatter::LONG)
    ->format($this->startsAt, $this->endsAt);
```

It works perfectly for most languages that I tried:

```
(en) December 3 – 4, 2020
(fr) 3 – 4 décembre 2020
(de) 3. – 4. Dezember 2020
```

But in Spanish (locale `es`) I get this (it even includes an extra white space at the end):

```
3 de – 4 de diciembre 
```

It should be:

```
3 – 4 de diciembre de 2020

(also common -> 3 – 4 de diciembre, 2020)
```

Maybe I did something wrong, but I wanted to report this issue just in case. Thanks!

**Comment by flack** [comment]
Hi & thanks for the report!

I've looked into it, and it seems our pattern parsing got confused by the ` de ` separator between day & month (and month & year). I've added a commit to better handle this situation, can you try again with current master and see if everything works as expected now?

**Comment by javiereguiluz** [comment]
Thanks for your quick reply and for looking into this!

I've just applied the changes of your commit and I can confirm that the issue is fixed. The range in `es` locale is now perfectly generated. Thanks a lot!

**Comment by flack** [comment]
alright, thnkas for testing. I've tagged a new release, so this should be good to go
